$.fn.responSlider=function(d){function k(){var g=a.find("ul:not(.responslider-paginate) li:visible"),e=g.next();b.reverse&&1>e.size()&&(e=a.find("ul:not(.responslider-paginate) li:first-child"));b.loadBar.activate&&b.autoPlay.activate&&(clearInterval(n),n=setInterval(q,b.autoPlay.delay),resetLoadedBar(a.find("div.responslider-loadbar")),animateLoadedBar(a.find("div.responslider-loadbar"),b.autoPlay.delay));if(1>e.size()||!f)return!1;a.find("ul.responslider-paginate li").removeClass("active");a.find("ul.responslider-paginate li:eq("+
e.index()+")").addClass("active");m=e.index()+1;f=!1;var c=a.find("ul li:visible").find("img").width();a.css({width:c});"slide"===b.effect?(e.children().css("left",c),e.show(),g.children().animate({right:g.find("img").width()},b.timer,function(){$(this).parent().hide()}),e.children().animate({left:0},b.timer,function(){$(this).css({left:"",right:""});f=!0})):"fade"===b.effect&&(e.show(),e.children().hide(),g.children().fadeTo(b.timer,0,function(){$(this).parent().hide()}),e.children().fadeTo(b.timer,
1,function(){f=!0}))}function p(){var c=a.find("ul:not(.responslider-paginate) li:visible"),e=c.prev();b.reverse&&1>e.size()&&(e=a.find("ul:not(.responslider-paginate) li:last-child"));b.loadBar.activate&&b.autoPlay.activate&&(clearInterval(n),n=setInterval(q,b.autoPlay.delay),resetLoadedBar(a.find("div.responslider-loadbar")),animateLoadedBar(a.find("div.responslider-loadbar"),b.autoPlay.delay));if(1>e.size()||!f)return!1;a.find("ul.responslider-paginate li").removeClass("active");a.find("ul.responslider-paginate li:eq("+
e.index()+")").addClass("active");m=e.index()+1;f=!1;var l=a.find("ul li:visible").find("img").width();a.css({width:l});"slide"===b.effect?(e.children().css("right",l),e.show(),c.children().animate({left:c.find("img").width()},b.timer,function(){$(this).css({left:"",right:""});$(this).parent().hide()}),e.children().animate({right:0},b.timer,function(){f=!0})):"fade"===b.effect&&(e.show(),e.children().hide(),c.children().fadeTo(b.timer,0,function(){$(this).parent().hide()}),e.children().fadeTo(b.timer,
1,function(){f=!0}))}var a=$(this);a.wrap("<div class='responslider-parent responslider-left'></div>");a.parent().wrap("<div id='responslider-globalcontent'></div>");var c=a.parent(),r=a.find("ul li").length;$(window).width();var y=$(window).height(),t=a.width(),u=a.height(),z=0,f=!0,n=0,b={responsHeight:!0,responsWidth:!0,effect:"fade",timer:400,paginateAlign:"middle",pagination:!0,navigation:!0,reverse:!0,loadBar:{activate:!1,color:"#000"},position:"center",onTop:{activate:!1,marginT:0,onload:!1},
autoPlay:{activate:!1,random:!1,delay:1E3},maxWidth:0,callBack:function(){}},m="fade"===b.effect?1:0;a.find("ul li").wrapInner("<div style='position:absolute;width:100%;'></div>");a.find("ul li").css("list-style-type","none");a.find("ul li img").css("max-width","100%");c.parent().css("visibility","hidden");d&&$.extend(b,d);b.loadBar.activate&&b.autoPlay.activate&&$("<div class='responslider-loadbar'></div>").insertBefore(a.find("ul")).css({height:2,"background-color":b.loadBar.color,width:0});d=b.navigation?
"":"none";$("<div class='responslider-left-navigation responslider-navigation'><div style='display:"+d+"' class='responslider-prev'></div></div>").insertBefore(a.parent());$("<div class='responslider-right-navigation responslider-navigation'><div style='display:"+d+"' class='responslider-next'></div></div>").insertAfter(a.parent());d=c.parent().find("div.responslider-next");var C=c.parent().find("div.responslider-prev"),A=c.parent().find("div.responslider-navigation:visible").children().height();
c.parent().find("div.responslider-navigation:visible").children().width();if(b.pagination){a.append("<ul class='responslider-paginate'></ul>");for(var h=1;h<=r;h++){var v=1==h?"active":"";a.find("ul.responslider-paginate").append("<li class='"+v+"' ><span>"+h+"</span></li>")}h--;switch(b.paginateAlign){case "left":a.find("ul.responslider-paginate").css("float","left");break;case "right":a.find("ul.responslider-paginate").css("float","right");break;default:var v=a.find("ul.responslider-paginate li").css("margin-left"),
D=a.find("ul.responslider-paginate li").css("margin-right"),E=a.find("ul.responslider-paginate li").css("padding-left"),F=a.find("ul.responslider-paginate li").css("padding-right");a.find("ul.responslider-paginate").width(a.find("ul.responslider-paginate li").width()*h+parseInt(v)*h+parseInt(D)*h+parseInt(E)*h+parseInt(F)*h+2*h);a.find("ul.responslider-paginate").css({margin:"0 auto"});var s=a.find("ul.responslider-paginate").width()}}window.onresize=function(){var g=a.find("ul li:visible img"),e=
new Image,l=0;e.src=g.attr("src");l=e.naturalWidth;nHeight=e.naturalHeight;g=a.offset().top+u+paginateHeight(a);e=$(window).scrollTop();g-=e;e=$(window).height()/g;e*=t;$(window).height()<g+paginateHeight(a)&&0<$(window).scrollTop()-(a.offset().top-2*a.height())?e<$(window).width()&&b.responsHeight?(a.css("width",e-paginateHeight(a)),c.css("width",e-paginateHeight(a))):b.responsWidth&&(a.css("width",$(window).width()),c.css("width",$(window).width())):b.responsWidth?(a.css("width",$(window).width()),
c.css("width",$(window).width())):b.responsHeight&&(a.css("width",l),c.css("width",l));s>a.width()?(a.find("ul.responslider-paginate").css("width",a.width()),a.css({height:a.find("ul li:visible").find("img").height()+2*paginateHeight(a)}),c.css({height:a.find("ul li:visible").find("img").height()+2*paginateHeight(a)})):(a.find("ul.responslider-paginate").css("width",s),a.css({height:a.find("ul li:visible").find("img").height()+paginateHeight(a)}),c.css({height:a.find("ul li:visible").find("img").height()+
paginateHeight(a)}));$(window).height()>y&&(y=$(window).height());b.onTop.activate&&$(window).scrollTop()<a.offset().top+a.height()&&0<$(window).scrollTop()-(a.offset().top-2*a.height())&&(l=a.offset().top-b.onTop.marginT,$("html, body").animate({scrollTop:l},300,function(){$(this).clearQueue()}));c.parent().css({width:a.width(),position:"relative",height:a.find("ul li:visible").find("img").height()+paginateHeight(a)});a.find("ul.responslider-paginate").css("top",a.find("ul li:visible").find("img").height()+
5);c.parent().find("div.responslider-prev, div.responslider-next").css("margin-top",a.find("ul li:visible").find("img").height()/2-A/2);c.css("margin-left",-(a.width()/2))};var w=0,B=setInterval(function(){var g=a.find("ul li:visible").find("img").width(),e=a.find("ul li:visible img"),l=new Image,d=0,f=0;l.src=e.attr("src");d=l.naturalWidth;f=l.naturalHeight;w++;5<w&&(d=a.find("ul li:visible").find("img").width(),f=a.find("ul li:visible").find("img").height());9<w&&clearInterval(B);c.parent().find("div.responslider-navigation").css({position:"absolute",
top:0,"z-index":9999});c.parent().find("div.responslider-left-navigation").css({left:"0"});c.parent().find("div.responslider-right-navigation").css({right:"0"});c.css({width:"100%",height:"100%",position:"absolute",left:"50%"});a.css({position:"relative",overflow:"hidden",width:"100%",height:"100%",padding:0,"-webkit-touch-callout":"none","-webkit-user-select":"none","-khtml-user-select":"none","-moz-user-select":"none","-ms-user-select":"none","user-select":"none"});a.find("ul:not(.responslider-paginate) li:nth-child(n+2)").hide();
if(0<g&&0<d&&0<f){a.css({width:d,height:f+paginateHeight(a)});0!=b.maxWidth?c.css("max-width",b.maxWidth):c.css("max-width",d);c.css("max-height",f+paginateHeight(a));c.css("margin-left",-(a.width()/2));a.css("max-height",f+paginateHeight(a));u=a.height();t=a.width();g=a.offset().top+u+paginateHeight(a);e=$(window).scrollTop();g-=e;e=$(window).height()/g;e*=t;$(window).height()<g+paginateHeight(a)&&0<$(window).scrollTop()-(a.offset().top-2*a.height())?e<$(window).width()&&b.responsHeight?(a.css("width",
e-paginateHeight(a)),c.css("width",e-paginateHeight(a))):b.responsWidth&&(a.css("width",$(window).width()),c.css("width",$(window).width())):b.responsWidth?(a.css("width",$(window).width()),c.css("width",$(window).width())):b.responsHeight&&(a.css("width",d),c.css("width",d));0!=b.maxWidth?(c.parent().css("max-width",b.maxWidth),c.css("max-width",b.maxWidth),a.css("max-width",b.maxWidth)):a.css("max-width",d);s>a.width()?(a.find("ul.responslider-paginate").css("width",a.width()),a.css({height:a.find("ul li:visible").find("img").height()+
2*paginateHeight(a)}),c.css({height:a.find("ul li:visible").find("img").height()+2*paginateHeight(a)})):(a.find("ul.responslider-paginate").css("width",s),a.css({height:a.find("ul li:visible").find("img").height()+paginateHeight(a)}),c.css({height:a.find("ul li:visible").find("img").height()+paginateHeight(a)}));c.css("margin-left",-(a.width()/2));a.parent().css({height:a.find("ul li:visible").find("img").height()+paginateHeight(a)});a.find("ul.responslider-paginate").css("top",a.find("ul li:visible").find("img").height()+
5);c.parent().find("div.responslider-prev, div.responslider-next").css("margin-top",a.find("ul li:visible").find("img").height()/2-A/2);switch(b.position){case "left":c.parent().css({"float":"left"});break;case "right":c.parent().css({"float":"right"});break;default:c.parent().css("margin","0 auto")}b.onTop.activate&&b.onTop.onload&&$(window).scrollTop()<a.offset().top+a.height()&&0<$(window).scrollTop()-(a.offset().top-2*a.height())&&(d=a.offset().top-b.onTop.marginT,$("body").animate({scrollTop:d},
300));c.parent().css({width:a.width(),position:"relative",height:a.find("ul li:visible").find("img").height()+paginateHeight(a)});c.parent().css("visibility","visible");clearInterval(B);b.callBack()}},200),q=function(c){if(!f)return!1;b.timer=b.autoPlay.delay<b.timer?b.autoPlay.delay:b.timer;b.autoPlay.random?(c=Math.floor(Math.random()*r),z===c&&(c+1<r?c++:c--),z=c,x(a.find("ul.responslider-paginate").find("li"),c)):(m=m===r?0:m,x(a.find("ul.responslider-paginate").find("li"),m++));b.loadBar.activate&&
b.autoPlay.activate&&animateLoadedBar(a.find("div.responslider-loadbar"),b.autoPlay.delay)};b.autoPlay.activate&&(b.loadBar.activate&&animateLoadedBar(a.find("div.responslider-loadbar"),b.autoPlay.delay),500>b.autoPlay.delay&&(b.autoPlay.delay=1E3),n=setInterval(q,b.autoPlay.delay));d.click(function(){k()});C.click(function(){p()});$(document).keydown(function(a){39==a.which?(a.preventDefault(),k()):37==a.which&&(a.preventDefault(),p())});if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent.toLowerCase()))try{a.on("swipeleft",
function(){p()}),a.on("swiperight",function(){k()})}catch(G){}var x=function(c,e){var d=c.index(),h=a.find("ul:not(.responslider-paginate) li:visible").index(),k=a.find("ul:not(.responslider-paginate) li:visible").find("img").width(),m=a.find("ul:not(.responslider-paginate) li:visible").children();e&&(d=e);b.loadBar.activate&&b.autoPlay.activate&&(clearInterval(n),n=setInterval(q,b.autoPlay.delay),resetLoadedBar(a.find("div.responslider-loadbar")),animateLoadedBar(a.find("div.responslider-loadbar"),
b.autoPlay.delay));setTimeout(function(){f=!0},b.timer);if(!f)return!1;f=!1;a.find("ul.responslider-paginate li").removeClass("active");a.find("ul.responslider-paginate li:eq("+d+")").addClass("active");if("slide"===b.effect)if(d>h)a.find("ul li:eq("+d+")").children().css("left",k),a.find("ul li:eq("+d+")").show(),m.animate({right:k},b.timer,function(){$(this).parent().hide();$(this).css({left:"",right:""})}),a.find("ul li:eq("+d+")").children().animate({left:0},b.timer,function(){$(this).css({left:"",
right:""});f=!0});else if(d<h)f=!1,a.find("ul li:eq("+d+")").children().css("right",k),a.find("ul li:eq("+d+")").show(),m.animate({left:k},b.timer,function(){$(this).parent().hide();$(this).css({left:"",right:""})}),a.find("ul li:eq("+d+")").children().animate({right:0},b.timer,function(){$(this).css({left:"",right:""});f=!0});else return!1;else"fade"===b.effect&&(f=!1,a.find("ul li:eq("+d+")").show(),a.find("ul li:eq("+d+")").children().hide(),a.find("ul li:eq("+h+")").children().fadeTo(b.timer,
0,function(){$(this).parent().hide()}),a.find("ul li:eq("+d+")").children().fadeTo(b.timer,1,function(){f=!0}))};a.find("ul.responslider-paginate").find("li").click(function(){m=$(this).index()+1;x($(this))})};function resetLoadedBar(d){d.clearQueue();d.stop();d.css("width",0)}function animateLoadedBar(d,k){d.animate({width:"100%"},k,function(){$(this).css("width",0)})}
function paginateHeight(d){var k=isNaN(parseInt(d.find("ul.responslider-paginate li").css("margin-top")))?0:parseInt(d.find("ul.responslider-paginate li").css("margin-top")),p=isNaN(parseInt(d.find("ul.responslider-paginate li").css("padding-top")))?0:parseInt(d.find("ul.responslider-paginate li").css("padding-top")),a=isNaN(parseInt(d.find("ul.responslider-paginate li").css("top")))?0:parseInt(d.find("ul.responslider-paginate li").css("top"));d=d.find("ul.responslider-paginate").height();return k+
p+a+d};
